version: '3'
services:

  quarkus-todo-db:
    image: 'postgres:13.1'
    environment:
      POSTGRES_USER: restcrud
      POSTGRES_PASSWORD: restcrud
      POSTGRES_DB: rest-crud
    ports:
      - 5432:5432
